# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.CharField(default=b'20160010145', max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
