# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAdvisor',
            fields=[
                ('roll_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
